name: "Descargar Sentencias"

on:
  workflow_dispatch:
    inputs:
      fecha:
        description: 'Fecha a descargar (YYYY-MM-DD)'
        required: true
        default: '2024-01-15'

jobs:
  descargar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Descargar sentencias
        run: |
          echo "📅 Descargando sentencias del día: ${{ github.event.inputs.fecha }}"
          python3 descargar_sentencias_api.py ${{ github.event.inputs.fecha }} ${{ github.event.inputs.fecha }}
      
      - name: Preparar para Supabase
        run: |
          echo "🔄 Preparando archivos para Supabase..."
          python3 preparar_para_supabase.py output/descarga_api
      
      - name: Upload resultados
        uses: actions/upload-artifact@v3
        with:
          name: sentencias-${{ github.event.inputs.fecha }}
          path: output/
          retention-days: 30
      
      - name: Resumen final
        run: |
          echo "✅ Descarga completada para: ${{ github.event.inputs.fecha }}"
          echo "📊 Archivos generados: $(find output/ -name "*.json" | wc -l)"
