name: "Test Workflow"

on:
  workflow_dispatch:
    inputs:
      fecha:
        description: 'Fecha a descargar (YYYY-MM-DD)'
        required: true
        default: '2024-01-15'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Test
        run: |
          echo "🧪 Probando workflow..."
          echo "Fecha recibida: ${{ github.event.inputs.fecha }}"
          echo "✅ Workflow funcionando correctamente"
